# 1、k: v # k v 之间 是空格区分 k:
# 2、属性有层级关系，使用下一行，空两个空格
# 3、左侧对齐的代表同一层级的属性
---
server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 10MB
  data:
    redis:
      host: 150.158.141.184
      port: 6379
      password: 123456

tea:
  name: "t1"
  age: "20"
  type: "math"

--- #下边是一个单独文档
a: b
person:
  name: '张三 \n 123'
  age: 18
  birth-day: 2010/10/10 12:12:12
  like: true
  child:
    name: "李四 \n 456"
    age: 20
    birth-day: 2018/10/10
    text:
      - abc
      - def
      - |
        dogs:
          - name: 小黑
            age: 3
          - name: 小白
            age: 2
      - >
        活动结束看大
        号节课第三
        带回家看
      - |
        dhhdh
        fjkdsl
        gflkd
  dogs:
    - name: 小黑
      age: 3
    - name: 小白
      age: 2
  cats:
    c1:
      name: 小蓝
      age: 3
    c2: { name: 小绿,age: 2 } #对象也可用{}表示

student:
  age: "20"
  name: "zxx"
  wight: 190

aClass1:
  name: aclass
  describe: "this is aClass"

### actuator 监控springboot项目
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always


############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true