server:
  port: 8080

rocketmq:
#  name-server: 150.158.27.19:9876
  producer:
    group: my-producer-group
  consumer:
    group: my-consumer-group
    topic: my-topic
  name-server: 192.168.3
    enable-msg-trace: true